<!DOCTYPE html>
<html lang="en">
<head>
  <title>Koofamiles</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style type="text/css">
   li{
   margin: 0 0 3px 0;
   }
  </style>
</head>
<body>

<div class="jumbotron text-center">
  <h1><a href="index.php">Koofamiles</a></h1>
      
     
</div>
  
<div class="container">  
  <div class="row">
    <div class="col-sm-12">
      <p>&nbsp;</p>

<h2><span style="font-weight: 400;">TERMS OF USE FOR MALAYSIA KOOFOOD CUSTOMERS</span></h2>
<p><em><span style="font-weight: 400;">Last modified: 21 SEPT 2018</span></em></p>
<p><strong>Important</strong><span style="font-weight: 400;">&ndash; please read these terms carefully. By using the Service (as defined below), you agree that you have read, understood, accepted and agreed with the Terms of Use (as defined below). You further agree to the representations made by yourself below. If you do not agree to or fall within the Terms of Use of the Service and wish to discontinue using the Service, please do not continue using the Application (as defined below) or the Service.</span></p>
<p><span style="font-weight: 400;">The Terms of Use stated herein (collectively, the &ldquo;Terms of Use&rdquo; or this &ldquo;Agreement&rdquo;) constitute a legal agreement between you and </span><strong>Koo Family Sdn. Bhd. Bhd(Company No. 1114536-V) </strong><span style="font-weight: 400;">(the &ldquo;Company&rdquo;). In order to use the Service you must agree to the Terms of Use that are set out below. By using the mobile application supplied to you by the Company (the &ldquo;Application&rdquo;), and downloading, installing or using any associated software supplied by the Company (the &ldquo;Software&rdquo;) which overall purpose is to enable persons seeking, inter alia, food delivery services to certain destinations to be matched with independent third party delivery service providers (collectively, the &ldquo;Service&rdquo;), you hereby expressly acknowledge and agree to be bound by the Terms of Use, and any future amendments and additions to the Terms of Use as published from time to time at </span><a href="http://www.koofamilies.com/"><span style="font-weight: 400;">http://www.KooFamilies.com</span></a> <span style="font-weight: 400;">or through the Application.</span></p>
<p><span style="font-weight: 400;">For the purpose of these Terms of Use, wherever the context so requires &ldquo;You&rdquo; or &ldquo;User&rdquo; shall mean any natural or legal person who has agreed to because a user on the Application by providing registration data while registering on the Application. The term &ldquo;We&rdquo;, &ldquo;Us&rdquo;, &ldquo;Our&rdquo; shall mean the Company.</span></p>
<p><span style="font-weight: 400;">The Company reserves the right to modify, vary and change the Terms of Use or its policies relating to the Service at any time as it deems fit. Such modifications, variations and or changes to the Terms of Use or its policies relating to the Service shall be effective after five (5) days upon the posting of an updated version at&nbsp;</span><a href="http://www.koofamilies.com/"><span style="font-weight: 400;">http://www.KooFamilies.com</span></a><span style="font-weight: 400;">. You agree that it shall be your responsibility to review the Terms of Use regularly and also the Terms of Use applicable to any country where you use the Service which may differ from the country where you registered for the Application (the &ldquo;Alternate Country&rdquo;) whereupon the continued use of the Service after any such changes&rsquo; effectiveness, whether or not reviewed by you, shall constitute your consent and acceptance to such changes. You further agree that usage of the Service in the Alternate Country shall be subject to the Terms of Use prevailing for the Alternate Country which can be found at </span><a href="http://www.koofamilies.com/"><span style="font-weight: 400;">http://www.KooFamilies.com</span></a></p>
<p><span style="font-weight: 400;">THE COMPANY IS A </span><strong>TECHNOLOGY COMPANY </strong><span style="font-weight: 400;">THAT DOES NOT PROVIDE TRANSPORTATION, FOOD AND BEVERAGE, COURIER OR DELIVERY SERVICES. THE COMPANY IS NOT A FOOD AND BEVERAGE MERCHANT, COURIER OR DELIVERY SERVICE PROVIDER, OR TRANSPORTATION SERVICE PROVIDER. THE SERVICE OF THE COMPANY IS TO LINK INDEPENDENT THIRD-PARTY FOOD DELIVERY SERVICE PROVIDERS (&ldquo;</span><strong>DELIVERY SERVICE PROVIDER</strong><span style="font-weight: 400;">&rdquo;) WITH APPLICATION USERS AND FOOD AND BEVERAGE SERVICE PROVIDERS AVAILABLE ON OUR APPLICATION (&ldquo;</span><strong>MERCHANT</strong><span style="font-weight: 400;">&rdquo;).</span></p>
<p><span style="font-weight: 400;">IT IS UP TO EACH DELIVERY SERVICE PROVIDER TO OFFER AND PROVIDE FOOD DELIVERY SERVICES TO YOU. THE MERCHANTS ALSO OPERATE INDEPENDENTLY OF THE COMPANY. THE SERVICE OF THE COMPANY DOES NOT NOR IS IT INTENDED TO PROVIDE FOOD AND BEVERAGE AND/OR DELIVERY SERVICES. THERE WILL BE NO ACT OF THE COMPANY THAT CAN BE CONSTRUED IN ANY WAY AS AN ACT OF A MERCHANT OR DELIVERY SERVICE PROVIDER. THE COMPANY WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY DELIVERY SERVICE PROVIDER OR MERCHANT. THE COMPANY IS NOT RESPONSIBLE OR LIABLE FOR THE MERCHANT&rsquo;S FOOD PREPARATION, FOOD HYGIENE AND SAFETY AND THE COMPANY DOES NOT VERIFY ANY MERCHANT&rsquo;S COMPLIANCE WITH APPLICABLE LAWS OR FOOD HYGIENE AND SAFETY REGULATIONS.</span></p>
<ol>
<li><span style="font-weight: 400;"> Representations and Warranties</span></li>
</ol>
<p><span style="font-weight: 400;">By using the Service, you expressly represent and warrant that you are legally entitled to accept and agree to the Terms of Use and that you are at least eighteen (18) years old. Without limiting the generality of the foregoing, the Service is not available to persons under the age of eighteen (18) or such persons that are forbidden for any reason whatsoever to enter into a contractual relationship. By using the Service, you further represent and warrant that you have the right, authority and capacity to use the Service and to abide by the Terms of Use. You further confirm that all the information which you provide shall be true and accurate. Your use of the Service is for your own sole, personal use. You undertake not to authorize others to use your identity or user status, and you may not assign or otherwise transfer your user account to any other person or entity. When using the Service, you agree to comply with all applicable laws whether in your home nation or otherwise in the country, state and city in which you are present while using the Service.</span></p>
<p><span style="font-weight: 400;">You may only access the Service using authorized means. It is your responsibility to check and ensure that you have downloaded the correct Software for your device. The Company is not liable if you do not have a compatible device or if you have downloaded the wrong version of the Software to your device. The Company reserves the right not to permit you to use the Service should you use the Application and/or the Software with an incompatible or unauthorized device or for purposes other than which the Software and/or the Application is intended to be used.</span></p>
<p><span style="font-weight: 400;">By using the Software or the Application, you agree that:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will only use the Service for lawful purposes;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will only use the Service for the purpose for which it is intended to be used;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not use the Service, the Application and/or the Software for sending or storing any unlawful material or for fraudulent purposes;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not use the Service, the Application and/or the Software to cause nuisance, annoyance, inconvenience or make fake bookings and/or orders;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not use the Application and/or the Software for purposes other than obtaining the Service;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not use the Service, or any content accessible through the Service, for any commercial purpose, including but not limited to contacting, advertising to, soliciting or selling to, any Merchant, Application user or Delivery Service Provider, unless the Company has given you specific consent to do so in writing;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not create or compile, directly or indirectly, any collection, compilation, or other directory from any content displayed through the Service except for your personal, noncommercial use;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not copy any content displayed through the Service and/or the Application, including but not limited to Merchants&rsquo; menu content and reviews, for republication in any format or media;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You shall not contact the third party transportation provider and/or Delivery Service Provider for purposes other than the Service;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You shall not intentionally or unintentionally cause or attempt to cause damage to the Delivery Service Provider;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not try to harm the Service, the Application and/or the Software in any way whatsoever;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will not copy, or distribute the Software or other content without written permission from the Company;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will only use the Software and/or the Application for your own use and will not resell either the Software or Service to a third party;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will keep secure and confidential your account password or any identification we provide you which allows access to the Service;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will provide the Company with proof of identity as it may reasonably request or require;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You agree to provide accurate, current and complete information as required for the Service and undertake the responsibility to maintain and update your information in a timely manner to keep it accurate, current and complete at all times during the term of this Agreement. You agree that the Company may rely on your information as accurate, current and complete. You acknowledge that if your information is untrue, inaccurate, not current or incomplete in any respect, the Company has the right but not the obligation to terminate this Agreement and your use of the Service at any time with or without notice;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You will only use an access point or data account which you are authorized to use;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You shall not employ any means to defraud the Company or enrich yourself, through any means, whether fraudulent or otherwise, through any event, promotion or campaign launched by the Company to encourage new subscription or usage of the Service by new or existing customers;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You are aware that when requesting food delivery services by SMS or use of the Service, standard telecommunication charges will apply;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You shall not cause a nuisance or behave in an inappropriate or disrespectful manner towards the Company or the third party transportation provider and/or Delivery Service Provider regardless of any misgivings that you may have against the Company or the Delivery Service Provider;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You shall not impair or circumvent the proper operation of the network which the Service operates on;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You agree that the Service is provided on a reasonable effort basis; and</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">You agree that your use of the Service will be subject to the Company&rsquo;s Privacy Policy as may be amended from time to time.</span></li>
</ul>
<p><span style="font-weight: 400;">You are responsible for ensuring that the delivery details entered by you on the Application are accurate and complete. The Company shall not be liable in the event of late delivery or non-delivery of food and beverage items that you order by reason of erroneous delivery details entered by you on the Application.</span></p>
<p><span style="font-weight: 400;">After the delivery of the food and beverage items, you shall solely be liable for demurrage or loss, damage, contamination, soiling or detention of the food and beverage items (including but not limited to containers) whether caused directly or indirectly by you or any person acting as servant, representative or independent contractor for or on behalf of you.</span></p>
<p><span style="font-weight: 400;">You agree to assume full responsibility and liability for all loss or damage suffered by yourself, the Delivery Service Provider, the Merchant, the Company or any third party as a result of any breach of the Terms of Use.</span></p>
<ol start="2">
<li><span style="font-weight: 400;"> Bookings</span></li>
</ol>
<p><span style="font-weight: 400;">The Application allows you to place orders for food and beverage from Merchants, such orders to be delivered to you by Delivery Service Providers, subject to the terms and conditions set out herein.</span></p>
<p><span style="font-weight: 400;">The Company does not own, sell or resell any food and beverage items and does not control the Merchants, the Delivery Service Providers or any services provided by them. You understand that any order that you place shall be subject to the product availability and delivery location serviceability of the Merchants and the Delivery Service Providers.</span></p>
<p><span style="font-weight: 400;">As a general rule, all food order and delivery bookings placed on the Application are treated as confirmed. However, upon your successful completion of a booking, the Merchant and/or the Delivery Service Provider may call you on the telephone or mobile number provided or otherwise contact you to confirm the details of the order, any change in the order (for instance, due to unavailability), the price to be paid, any change in price of the order, and/or the estimated delivery time. For avoidance of doubt, the Company is not involved in and will not be responsible for any separate arrangement between you and the Merchant and/or Delivery Service Provider regarding the amendment and/or cancellation of orders made by you where such arrangement is not confirmed and recorded on the Application.</span></p>
<p><span style="font-weight: 400;">The Company, Merchant and Delivery Service Provider reserve the right to not to process your booking in the event you are unavailable on the phone at the time of the call for confirming the order or otherwise uncontactable, and in such event the provisions relating to cancellation below shall be applicable.</span></p>
<p><span style="font-weight: 400;">The prices of food and beverage items reflected in the Application are determined solely by the Merchant and are listed for information only.</span></p>
<p><span style="font-weight: 400;">Prices of food and beverage items as reflected in the Application may, for reasons such as technical issue, typographical error or outdated product information supplied by Merchant, be incorrectly reflected and in such event Merchant may cancel your order(s).</span></p>
<p><span style="font-weight: 400;">The Merchant shall be solely responsible for any warranty in relation to, and quality of, the food and beverage products sold to you and in no event shall the foregoing be the responsibility of the Company.</span></p>
<ol start="3">
<li><span style="font-weight: 400;"> Booking Cancellation</span></li>
</ol>
<p><span style="font-weight: 400;">As a general rule you shall not be entitled to cancel your booking once you have received confirmation of the same.</span></p>
<p><span style="font-weight: 400;">If you cancel your booking after it has been confirmed, you remain liable to pay the delivery fee regardless of whether the food and beverage items have been prepared by the Merchant.</span></p>
<p><span style="font-weight: 400;">You remain liable to pay the order value in full where (i) cancellation is made by you after the Merchant starts food/beverage preparation or (ii) you are not present or do not show up at the designated delivery location or (iii) you are unreachable physically or uncontactable after 10 minutes from the time that the Delivery Service Provider arrives the designated delivery location.</span></p>
<p><span style="font-weight: 400;">The Company, Merchant and Delivery Service Provider will have the right to not proceed with your booking in the following circumstances:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">where the requested delivery location falls outside the delivery zone offered on the Application;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">failure to contact you by phone or other means at the time of confirming the order booking;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">failure to deliver your order due to lack of information, direction or authorisation from you at the time of delivery; or</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">unavailability of all the items ordered by you at the time of booking.</span></li>
</ul>
<ol start="4">
<li><span style="font-weight: 400;"> Payment</span></li>
</ol>
<p><span style="font-weight: 400;">You may choose to pay for the transportation services by cash or where available, by credit card and or debit card, by Koo Coins or where available by such other methods as are made available in the Application.</span></p>
<p><span style="font-weight: 400;">The terms of all non-cash payments made by you through the Application will be governed by the Koo Coins Terms of Use, accessible via the&nbsp;</span><a href="http://www.koofamilies.com/"><span style="font-weight: 400;">http://www.KooFamilies.com</span></a> <span style="font-weight: 400;">website.</span></p>
<ol start="5">
<li><span style="font-weight: 400;"> KooRewards Loyalty Programme</span></li>
</ol>
<p><span style="font-weight: 400;">By using the Application, you will automatically be a member of the loyalty programme named &ldquo;KooRewards Loyalty Programme&rdquo; operated by the Company and/or its Affiliates.</span></p>
<p><span style="font-weight: 400;">The terms of the KooRewards Loyalty Programme will be governed by the Koo Terms of Use, accessible via the </span><a href="http://www.koofamilies.com/"><span style="font-weight: 400;">http://www.KooFamilies.com</span></a> <span style="font-weight: 400;">website.</span></p>
<ol start="6">
<li><span style="font-weight: 400;"> Taxes</span></li>
</ol>
<p><span style="font-weight: 400;">You agree that this Agreement shall be subject to all prevailing statutory taxes, duties, fees, charges and/or costs, however denominated, as may be in force and in connection with any future taxes that may be introduced at any point of time. You further agree to use your best efforts to do everything necessary and required by the relevant laws to enable, assist and/or defend the Company to claim or verify any input tax credit, set off, rebate or refund in respect of any taxes paid or payable in connection with the Service supplied under this Agreement.</span></p>
<ol start="7">
<li><span style="font-weight: 400;"> License Grant &amp; Restrictions</span></li>
</ol>
<p><span style="font-weight: 400;">The Company and its licensors, where applicable, hereby grants you a revocable, non-exclusive, non-transferable, non-assignable, personal, limited license to use the Application and/or the Software, solely for your own personal, non-commercial purposes, subject to the Terms of Use herein. All rights not expressly granted to you are reserved by the Company and its licensors.</span></p>
<p><span style="font-weight: 400;">You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Application and/or the Software in any way; (ii) modify or make derivative works based on the Application and/or the Software; (iii) create internet &ldquo;links&rdquo; to the Application or &ldquo;frame&rdquo; or &ldquo;mirror&rdquo; the Software on any other server or wireless or internet-based device; (iv) reverse engineer or access the Software in order to (a) build a competitive product or service, (b) build a product using similar ideas, features, functions or graphics of the Application and/or the Software, or (c) copy any ideas, features, functions or graphics of the Application and/or the Software; (v) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Application and/or the Software; (vi) use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, &ldquo;data mine&rdquo;, or in any way reproduce or circumvent the navigational structure or presentation of the Service or its contents; (vii) post, distribute or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior consent of the owner of such proprietary rights; or (viii) remove any copyright, trademark or other proprietary rights notices contained in the Service.</span></p>
<p><span style="font-weight: 400;">You may use the Software and/or the Application only for your personal, non-commercial purposes and shall not use the Software and/or the Application to: (i) send spam or otherwise duplicative or unsolicited messages; (ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including but not limited to materials harmful to children or violative of third party privacy rights; (iii) send material containing software viruses, worms, trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Software and/or the Application or the data contained therein; (v) attempt to gain unauthorized access to the Software and/or the Application or its related systems or networks; (vi) impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity or (vii) engage in any conduct that could possibly damage the Company&rsquo;s reputation or amount to being disreputable.</span></p>
<ol start="8">
<li><span style="font-weight: 400;"> Intellectual Property Ownership</span></li>
</ol>
<p><span style="font-weight: 400;">The Company and its licensors, where applicable, shall own all right, title and interest, including all related intellectual property rights, in and to the Software and/or the Application and by extension, the Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Service. The Terms of Use do not constitute a sale agreement and do not convey to you any rights of ownership in or related to the Service, the Software and/or the Application, or any intellectual property rights owned by the Company and/or its licensors. The Company&rsquo;s name, the Company&rsquo;s logo, the Service, the Software and/or the Application and the Merchants&rsquo; and Delivery Service Providers&rsquo; names, logos and images and the product names associated with the Software and/or the Application are trademarks or otherwise subject to intellectual property rights of the Company or third parties, and no right or license is granted to use them. For the avoidance of doubt, the term the Software and the Application herein shall include its respective components, processes and design in its entirety.</span></p>
<ol start="9">
<li><span style="font-weight: 400;"> Confidentiality</span></li>
</ol>
<p><span style="font-weight: 400;">You shall maintain in confidence all information and data relating to the Company, its services, products, business affairs, marketing and promotion plans or other operations and its associated companies which are disclosed to you by or on behalf of the Company (whether orally or in writing and whether before, on or after the date of this Agreement) or which are otherwise directly or indirectly acquired by you from the Company, or any of its affiliated companies, or created in the course of this Agreement. You shall further ensure that you only use such confidential information in order to use the Service, and shall not without the Company&rsquo;s prior written consent, disclose such information to any third-party nor use it for any other purpose.</span></p>
<p><span style="font-weight: 400;">The above obligations of confidentiality shall not apply to the extent that you can show that the relevant information:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">was at the time of receipt already in your possession;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">is, or becomes in the future, public knowledge through no fault or omission of you;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">was received from a third-party having the right to disclose it; or</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">is required to be disclosed by law.</span></li>
</ul>
<ol start="10">
<li><span style="font-weight: 400;"> Data Privacy &amp; Personal Data Protection Policy</span></li>
</ol>
<p><span style="font-weight: 400;">You agree and consent to the Company collecting, using, disclosing and processing your Personal Data for the Purposes and in the manner as identified hereunder.</span></p>
<p><span style="font-weight: 400;">For the purposes of this Agreement, &ldquo;Personal Data&rdquo; means information about you, from which you are identifiable, directly or indirectly, including but not limited to your name, identification card number, birth certificate number, passport number, nationality, address, telephone number, credit or debit card details, race, gender, date of birth, email address, any information about you which you have provided to the Company by any means and/or any information about you that has been or may be collected, stored, used and processed by the Company.</span></p>
<p><span style="font-weight: 400;">The provision of your Personal Data is voluntary. However, if you do not provide the Company your Personal Data, your request for the Application may be incomplete and the Company will not be able to process your Personal Data for the Purposes outlined below and may cause the Company to be unable to allow you to use the Service.</span></p>
<p><span style="font-weight: 400;">The Company may collect, use, disclose and process your Personal Data for business and activities of the Company which shall include, without limitation the following (the &ldquo;Purposes&rdquo;):</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">to perform the Company&rsquo;s obligations in respect of any contract entered with you;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to provide you with any services pursuant to the Terms of Use herein;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">process, manage or verify your application for the Service pursuant to the Terms of Use herein;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to validate and/or process payments pursuant to the Terms of Use herein;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to process any refunds, rebates and or charges pursuant to the Terms of Use herein;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to facilitate or enable any checks as may be required pursuant to the Terms of Use herein;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to develop, enhance and provide what is required pursuant to the Terms of Use herein to meet your needs;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">for internal administrative purposes, such as auditing, data analysis, database records;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">for purposes of detection, prevention and prosecution of crime including in relation to its obligations under any applicable laws, regulations, guidelines or notices issued by any government or regulatory authority (whether in Malaysia or overseas);</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">for the Company to comply with its obligations any applicable laws, regulations, guidelines or notices issued by any government or regulatory authority (whether in Malaysia or overseas including disclosing such Personal Data to Malaysia and overseas law enforcement agencies or courts);</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to respond to questions, comments and feedback from you; and</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">in accordance with any applicable laws permitting the use, collection, disclosure and processing of Personal Data.</span></li>
</ul>
<p><span style="font-weight: 400;">In addition to the above, the Company may wish to communicate with you either by email, telephone or text message in relation to the following matters (the &ldquo;Marketing Purposes&rdquo;):</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">to process your participation in any events, promotions, activities, focus groups, research studies, contests, promotions, polls, surveys or any productions and to communicate with you regarding your attendance thereto;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to send you alerts, newsletters, updates, mailers, promotional materials, special privileges, festive greetings from the Company, its partners, advertisers and or sponsors;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to notify and invite you to events or activities organized by the Company, its partners, advertisers, and or sponsors; and/or</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">to share your Personal Data amongst the companies within the Company&rsquo;s group of companies comprising the subsidiaries, associate companies and or jointly controlled entities of the holding company of the group (the &ldquo;Group&rdquo;) and with the Company&rsquo;s and Group&rsquo;s agents, third party providers, developers, advertisers, partners, event companies or sponsors who may communicate with you for any reasons whatsoever.</span></li>
</ul>
<p><span style="font-weight: 400;">If you do not consent to the Company processing your Personal Data for any of the Marketing Purposes, please notify the Company at the following email address: </span><span style="font-weight: 400;">Admin@koofamilies.com</span></p>
<p><span style="font-weight: 400;">If any of the Personal Data that you have provided to us changes, for example, if you change your e- mail address, telephone number, payment details or if you wish to cancel your account or withdraw your permission to receive communications for Marketing Purposes, please update your details by sending your request to the support contact details at the following email address: </span><span style="font-weight: 400;">Admin@koofamilies.com</span></p>
<p><span style="font-weight: 400;">The Company will, to the best of its abilities, effect such changes as requested within fourteen (14) working days of receipt of such notice of change.</span></p>
<p><span style="font-weight: 400;">The Company is committed to full compliance with the provisions of the Personal Data Protection Act 2010 and has appointed a Personal Data Protection Officer for these purposes. Such officer may be communicated with in writing at the above email address.</span></p>
<ol start="11">
<li><span style="font-weight: 400;"> Third Party Interactions</span></li>
</ol>
<p><span style="font-weight: 400;">During use of the Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of third party providers, advertisers or sponsors showing their goods and/or services through the Service, the Software and/or the Application. Any such activity, and any terms, conditions, warranties or representations associated with such activity, is solely between you and the applicable third-party. The Company and its licensors shall have no liability, obligation or responsibility for any such correspondence, purchase, transaction or promotion between you and any such third-party. The Group does not endorse any applications or sites on the Internet that are linked through the Service, the Application and/or the Software, and in no event, shall the Company, its licensors or the Group be responsible for any content, products, services or other materials on or available from such sites or third party providers. The Company provides the Service to you pursuant to the Terms of Use. You recognize, however, that certain third party providers of transportation, goods and/or services may require your agreement to additional or different Terms of Use prior to your use of or access to such goods or services, and the Company is not a party to and disclaims any and all responsibility and/or liability arising from such agreements between you and the third party providers.</span></p>
<p><span style="font-weight: 400;">The Company may rely on third party advertising and marketing supplied through the Service and other mechanisms to subsidize the Service and/or to earn additional revenue. By agreeing to the Terms of Use you agree to receive such advertising and marketing. If you do not want to receive such advertising, you should notify us in writing or in accordance with the procedure determined by the Company. The Company reserves the right to charge you a higher fee for or deny you use of the Service should you choose not to receive these advertising services. This higher fee, if applicable, will be posted on the Company&rsquo;s website located at http://www.grab.com. You agree and allow the Company to compile and release information regarding you and your use of the Service on an anonymous basis as part of a customer profile or similar report or analysis. You agree that it is your responsibility to take all precautions in all actions and interactions with any Merchant, third party transportation provider, Delivery Service Provider, other third party providers, advertisers and/or sponsors you interact with through the Service and/or advertising or marketing material supplied through the Service.</span></p>
<ol start="12">
<li><span style="font-weight: 400;"> Indemnification</span></li>
</ol>
<p><span style="font-weight: 400;">By agreeing to the Terms of Use upon using the Service, you agree that you shall defend, indemnify and hold the Company, its licensors and each such party&rsquo;s parent organizations, subsidiaries, affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys&rsquo; fees and costs and/or regulatory action) arising out of or in connection with: (a) your use of the Service, the Software and/or the Application in your dealings with the third party merchants, transportation and/or delivery service providers, third party providers, partners, advertisers and/or sponsors, or (b) your violation or breach of any of the Terms of Use or any applicable law or regulation, whether or not referenced herein, or (c) your violation of any rights of any third party, including any merchant, or third party transportation and/or delivery service providers arranged via the Service, or (d) your use or misuse of the Service, the Software and/or the Application.</span></p>
<ol start="13">
<li><span style="font-weight: 400;"> Disclaimer of Warranties</span></li>
</ol>
<p><span style="font-weight: 400;">THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE. THE COMPANY DOES NOT REPRESENT OR WARRANT THAT (A) THE USE OF THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA, (B) THE SERVICE WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (C) ANY STORED DATA WILL BE ACCURATE OR RELIABLE, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIALS PURCHASED OR OBTAINED BY YOU THROUGH THE APPLICATION WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (E) ERRORS OR DEFECTS IN THE APPLICATION AND/OR THE SOFTWARE WILL BE CORRECTED, OR (F) THE APPLICATION OR THE SERVER(S) THAT MAKE THE APPLICATION AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (G) THE APPLICATION AND/OR THE SOFTWARE TRACKS YOU OR THE VEHICLE, BICYCLE OR MOBILITY DEVICE USED BY THE THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICE PROVIDER. THE SERVICE IS PROVIDED TO YOU STRICTLY ON AN &ldquo;AS IS&rdquo; BASIS. ALL CONDITIONS, REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS, ARE HEREBY EXCLUDED AND DISCLAIMED TO THE HIGHEST AND MAXIMUM EXTENT.</span></p>
<p><span style="font-weight: 400;">THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE AS TO THE RELIABILITY, SAFETY, TIMELINESS, QUALITY, SUITABILITY OR AVAILABILITY OF ANY PRODUCTS OR SERVICES, INCLUDING BUT NOT LIMITED TO MERCHANTS&rsquo; PRODUCTS, THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICES OR OTHER PRODUCTS AND SERVICES OBTAINED BY OR FROM THIRD PARTIES THROUGH THE USE OF THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE. YOU ACKNOWLEDGE AND AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SERVICE, AND ANY THIRD PARTY PRODUCTS AND SERVICES, INCLUDING BUT NOT LIMITED TO MERCHANTS&rsquo; PRODUCTS, THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICES OR OTHER PRODUCTS AND SERVICES REMAINS SOLELY AND ABSOLUTELY WITH YOU AND YOU SHALL HAVE NO RECOURSE WHATSOEVER TO THE COMPANY.</span></p>
<ol start="14">
<li><span style="font-weight: 400;"> Internet Delays</span></li>
</ol>
<p><span style="font-weight: 400;">THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS INCLUDING THE DEVICE USED BY YOU OR THE MERCHANT OR THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICE PROVIDER BEING FAULTY, NOT CONNECTED, OUT OF RANGE, SWITCHED OFF OR NOT FUNCTIONING. THE COMPANY IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, DAMAGES OR LOSSES RESULTING FROM SUCH PROBLEMS.</span></p>
<ol start="15">
<li><span style="font-weight: 400;"> Limitation of Liability</span></li>
</ol>
<p><span style="font-weight: 400;">ANY CLAIMS AGAINST THE COMPANY BY YOU SHALL IN ANY EVENT BE LIMITED TO THE AGGREGATE AMOUNT OF ALL AMOUNTS ACTUALLY PAID BY AND/OR DUE FROM YOU IN UTILISING THE SERVICE DURING THE EVENT GIVING RISE TO SUCH CLAIMS. IN NO EVENT SHALL THE COMPANY AND/OR ITS LICENSORS BE LIABLE TO YOU OR ANYONE FOR ANY DIRECT, INDIRECT, PUNITIVE, ECONOMIC, FUTURE SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OR LOSSES OF ANY TYPE OR KIND (INCLUDING PERSONAL INJURY, EMOTIONAL DISTRESS AND LOSS OF DATA, GOODS, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE). THE COMPANY AND/OR ITS LICENSORS SHALL NOT BE LIABLE FOR ANY LOSS, DAMAGE OR INJURY WHICH MAY BE INCURRED BY OR CAUSED TO YOU OR TO ANY PERSON FOR WHOM YOU HAVE BOOKED THE SERVICE, INCLUDING BUT NOT LIMITED TO LOSS, DAMAGE OR INJURY ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE INCLUDING BUT NOT LIMITED TO THE USE OR INABILITY TO USE THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE, ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY THIRD PARTY PROVIDER, MERCHANT, ADVERTISER OR SPONSOR WHOSE ADVERTISING APPEARS ON THE WEBSITE OR IS REFERRED TO BY THE SERVICE, THE APPLICATION AND/OR THE SOFTWARE, EVEN IF THE COMPANY AND/OR ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</span></p>
<p><span style="font-weight: 400;">THE COMPANY DOES NOT AND WILL NOT ASSESS NOR MONITOR THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD PARTY PROVIDERS INCLUDING THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICE PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE THIRD PARTY PROVIDERS INCLUDING THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICE PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS.</span></p>
<p><span style="font-weight: 400;">THE COMPANY WILL NOT BE A PARTY TO DISPUTES, NEGOTIATIONS OF DISPUTES BETWEEN YOU AND SUCH THIRD PARTY PROVIDERS INCLUDING THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICE PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS. UNLESS YOU ARE A CORPORATE CUSTOMER WITH A CURRENT CORPORATE ACCOUNT WITH THE COMPANY, THE COMPANY CANNOT AND WILL NOT PLAY ANY ROLE IN MANAGING PAYMENTS BETWEEN YOU AND THE THIRD PARTY PROVIDERS, INCLUDING THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICE PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING SERVICES AND PRODUCTS OFFERED VIA THE SERVICE, THE SOFTWARE AND/OR THE APPLICATION (WITH ALL ITS IMPLICATIONS) RESTS SOLELY WITH AND ON YOU. YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE SERVICE, THE SOFTWARE AND/OR THE APPLICATION, OR IN ANY WAY RELATED TO THE THIRD PARTIES INCLUDING THIRD PARTY TRANSPORTATION PROVIDERS, AND/OR DELIVERY SERVICE PROVIDERS, MERCHANTS, ADVERTISERS AND/OR SPONSORS INTRODUCED TO YOU BY THE SERVICE, THE SOFTWARE AND/OR THE APPLICATION.</span></p>
<p><span style="font-weight: 400;">THE QUALITY OF PRODUCTS AND THIRD PARTY TRANSPORTATION AND/OR DELIVERY SERVICES ORDERED OR SCHEDULED THROUGH THE USE OF THE SERVICE IS ENTIRELY THE RESPONSIBILITY OF THE THIRD PARTY PROVIDER WHO ULTIMATELY PROVIDES SUCH PRODUCTS, TRANSPORTATION AND/OR DELIVERY SERVICES TO YOU. YOU UNDERSTAND, THEREFORE, THAT BY USING THE SERVICE, YOU MAY BE EXPOSED TO PRODUCTS, TRANSPORTATION OR DELIVERY THAT IS POTENTIALLY DANGEROUS, OFFENSIVE, HARMFUL TO MINORS, UNSAFE OR OTHERWISE OBJECTIONABLE, AND THAT YOU USE THE SERVICE AT YOUR OWN RISK.</span></p>
<ol start="16">
<li><span style="font-weight: 400;"> Notice</span></li>
</ol>
<p><span style="font-weight: 400;">The Company may give notice by means of a general notice on the Application, electronic mail to your email address in the records of the Company, or by written communication sent by registered mail or pre-paid post to your address in the record of the Company. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by registered mail or pre-paid post) or 1 hour after sending (if sent by email). You may give notice to the Company (such notice shall be deemed given when received by the Company) by letter sent by courier or registered mail to the Company using the contact details as provided in the Application.</span></p>
<ol start="17">
<li><span style="font-weight: 400;"> Assignment</span></li>
</ol>
<p><span style="font-weight: 400;">This Agreement as constituted by the Terms of Use as modified from time to time may not be assigned by you without the prior written approval of the Company but may be assigned without your consent by the Company. Any purported assignment by you in violation of this section shall be void.</span></p>
<ol start="18">
<li><span style="font-weight: 400;"> General</span></li>
</ol>
<p><span style="font-weight: 400;">This Agreement shall be governed by Malaysia law, without regard to the choice or conflicts of law provisions of any jurisdiction, and any disputes, actions, claims or causes of action arising out of or in connection with the Terms and Conditions or the Service shall be subject to the exclusive jurisdiction of the courts of Malaysia to which you hereby agree to submit to.</span></p>
<p><span style="font-weight: 400;">Enforcement of Malaysia Court Decision in Alternate Country</span></p>
<p><span style="font-weight: 400;">In the event that the law in an Alternate Country does not allow jurisdiction to be that of the courts of Malaysia or where judgment of a Malaysia court is unenforceable in the Alternate Country, unresolved disputes shall be referred to the Asian International Arbitration Centre (&ldquo;AIAC&rdquo;), in accordance with the Rules of the AIAC as modified or amended from time to time (the &ldquo;Rules&rdquo;) by a sole arbitrator appointed by the mutual agreement of you and the Company (the &ldquo;Arbitrator&rdquo;). If you and the Company are unable to agree on an arbitrator, the Arbitrator shall be appointed by the President of AIAC in accordance with the Rules. The seat and venue of the arbitration shall be Malaysia, in the English language and the fees of the Arbitrator shall be borne equally by you and the Company, provided that the Arbitrator may require that such fees be borne in such other manner as the Arbitrator determines is required in order for this arbitration clause to be enforceable under applicable law.</span></p>
<p><span style="font-weight: 400;">No joint venture, partnership, employment, or agency relationship exists between you, the Company or any third party provider as a result of the Terms of Use or use of the Service.</span></p>
<p><span style="font-weight: 400;">If any provision of the Terms of Use is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. This shall, without limitation, also apply to the applicable law and jurisdiction as stipulated above.</span></p>
<p><span style="font-weight: 400;">The failure of the Company to enforce any right or provision in the Terms of Use shall not constitute a waiver of such right or provision unless acknowledged and agreed to by the Company in writing. The Terms of Use comprises the entire agreement between you and the Company and supersedes all prior or contemporaneous negotiations or discussions, whether written or oral (if any) between the parties regarding the subject matter contained herein.</span></p>
<p><span style="font-weight: 400;">You hereby agree that the Company is entitled to terminate this Agreement immediately in the event that you are found to be in breach of any of the terms stipulated in this Agreement. For the avoidance of doubt, the termination of this Agreement shall not require the Company to compensate, reimburse or cover any cost incurred by you in the course of you acquiring services from any third party service provider under this Agreement.</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
    </div>
    
  </div>
  <!-- Footer -->
<footer class="page-footer font-small indigo">


    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://www.koofamilies.com/"> koofamiles.com</a>
    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->
</div>

</body>
</html>
